// Extension REST client

GET https://notes-api-ggzj.onrender.com/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MDdjNDcwODNmOWRlNzFkMDM1YjliYSIsInVzZXJuYW1lIjoiam9obiIsImlhdCI6MTY3ODI4ODY5NywiZXhwIjoxNjc4ODkzNDk3fQ.lUUKuTc2L7wAIRhLinwq3QiJE6ivWL7Eu4QrKvf9dfU
