// Extension REST client

PUT http://localhost:3001/api/notes/6407c4fc83f9de71d035b9be
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MDdjNDcwODNmOWRlNzFkMDM1YjliYSIsInVzZXJuYW1lIjoiam9obiIsImlhdCI6MTY3ODIzOTc3MiwiZXhwIjoxNjc4ODQ0NTcyfQ.DvKYclxhW1rsf39jbRJ2yQCeIkF8mWILUvLZwU_VFZo

{
  "content": "Updated note content"
}