// Extension REST client

DELETE https://notes-api-ggzj.onrender.com/api/notes/6407b4e973e57c4f6034d8b1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MDdhZWYxNzEzYmJmM2ZhNDc0Y2IzZiIsInVzZXJuYW1lIjoiam9obiIsImlhdCI6MTY3ODIyNjIzOCwiZXhwIjoxNjc4ODMxMDM4fQ.uQWUJL9biBAJcOQr1Ci-uJUTZcTLsh7mBWAkwZHLQGM
