// Extension REST client

POST https://notes-api-ggzj.onrender.com/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MDdjNGU0ODNmOWRlNzFkMDM1YjliZCIsInVzZXJuYW1lIjoiamFuZSIsImlhdCI6MTY3ODIzMDc2NSwiZXhwIjoxNjc4ODM1NTY1fQ.Pn3ZD6eQRLhilPdCep7N67H0X9s89Vk-y_CAHZZ6348

{
  "content": "New note test"
}